;;-*-coding: emacs-mule;-*-
(define-abbrev-table 'awk-mode-abbrev-table '(
    ))

(define-abbrev-table 'bsh-script-mode-abbrev-table '(
    ))

(define-abbrev-table 'c++-mode-abbrev-table '(
    ))

(define-abbrev-table 'c-mode-abbrev-table '(
    ))

(define-abbrev-table 'comint-mode-abbrev-table '(
    ))

(define-abbrev-table 'edebug-eval-mode-abbrev-table '(
    ))

(define-abbrev-table 'fundamental-mode-abbrev-table '(
    ))

(define-abbrev-table 'global-abbrev-table '(
    ))

(define-abbrev-table 'html-helper-mode-abbrev-table '(
    ))

(define-abbrev-table 'idl-mode-abbrev-table '(
    ))

(define-abbrev-table 'java-mode-abbrev-table '(
    ))

(define-abbrev-table 'jde-mode-abbrev-table '(
    ("catch" "catch" c-electric-continued-statement 0)
    ("else" "else" c-electric-continued-statement 0)
    ("finally" "finally" c-electric-continued-statement 0)
    ("while" "while" c-electric-continued-statement 0)
    ))

(define-abbrev-table 'jde-run-mode-abbrev-table '(
    ))

(define-abbrev-table 'lisp-mode-abbrev-table '(
    ))

(define-abbrev-table 'objc-mode-abbrev-table '(
    ))

(define-abbrev-table 'php-mode-abbrev-table '(
    ))

(define-abbrev-table 'pike-mode-abbrev-table '(
    ))

(define-abbrev-table 'rails-script:output-mode-abbrev-table '(
    ))

(define-abbrev-table 'rails-test:compilation-mode-abbrev-table '(
    ))

(define-abbrev-table 'ruby-mode-abbrev-table '(
    ))

(define-abbrev-table 'select-tags-table-mode-abbrev-table '(
    ))

(define-abbrev-table 'shell-mode-abbrev-table '(
    ))

(define-abbrev-table 'sql-mode-abbrev-table '(
    ))

(define-abbrev-table 'text-mode-abbrev-table '(
    ))

(define-abbrev-table 'visual-basic-mode-abbrev-table '(
    ("aggregate" "Aggregate" nil 0)
    ("and" "And" nil 0)
    ("app" "App" nil 0)
    ("appactivate" "AppActivate" nil 0)
    ("application" "Application" nil 0)
    ("array" "Array" nil 0)
    ("as" "As" nil 0)
    ("asc" "Asc" nil 0)
    ("ascb" "AscB" nil 0)
    ("atn" "Atn" nil 0)
    ("beep" "Beep" nil 0)
    ("begintrans" "BeginTrans" nil 0)
    ("boolean" "Boolean" nil 0)
    ("byval" "ByVal" nil 0)
    ("call" "Call" nil 0)
    ("case" "Case" nil 0)
    ("cbool" "CBool" nil 0)
    ("cbyte" "CByte" nil 0)
    ("ccur" "CCur" nil 0)
    ("cdate" "CDate" nil 0)
    ("cdbl" "CDbl" nil 0)
    ("character" "Character" nil 0)
    ("chdir" "ChDir" nil 0)
    ("chdrive" "ChDrive" nil 0)
    ("choose" "Choose" nil 0)
    ("chr" "Chr" nil 0)
    ("chrb" "ChrB" nil 0)
    ("cint" "CInt" nil 0)
    ("classmodule" "ClassModule" nil 0)
    ("clipboard" "Clipboard" nil 0)
    ("clng" "CLng" nil 0)
    ("close" "Close" nil 0)
    ("collection" "Collection" nil 0)
    ("column" "Column" nil 0)
    ("columns" "Columns" nil 0)
    ("command" "Command" nil 0)
    ("committrans" "CommitTrans" nil 0)
    ("compactdatabase" "CompactDatabase" nil 0)
    ("component" "Component" nil 0)
    ("components" "Components" nil 0)
    ("const" "Const" nil 0)
    ("container" "Container" nil 0)
    ("containers" "Containers" nil 0)
    ("cos" "Cos" nil 0)
    ("createdatabase" "CreateDatabase" nil 0)
    ("createobject" "CreateObject" nil 0)
    ("csng" "CSng" nil 0)
    ("cstr" "CStr" nil 0)
    ("curdir" "CurDir" nil 0)
    ("currency" "Currency" nil 0)
    ("cvar" "CVar" nil 0)
    ("cverr" "CVErr" nil 0)
    ("data" "Data" nil 0)
    ("database" "Database" nil 0)
    ("databases" "Databases" nil 0)
    ("date" "Date" nil 0)
    ("dateadd" "DateAdd" nil 0)
    ("datediff" "DateDiff" nil 0)
    ("datepart" "DatePart" nil 0)
    ("dateserial" "DateSerial" nil 0)
    ("datevalue" "DateValue" nil 0)
    ("day" "Day" nil 0)
    ("dbengine" "DBEngine" nil 0)
    ("ddb" "DDB" nil 0)
    ("debug" "Debug" nil 0)
    ("declare" "Declare" nil 0)
    ("deftype" "Deftype" nil 0)
    ("deletesetting" "DeleteSetting" nil 0)
    ("dim" "Dim" nil 0)
    ("dir" "Dir" nil 0)
    ("do" "Do" nil 0)
    ("domain" "Domain" nil 0)
    ("double" "Double" nil 0)
    ("dynaset" "Dynaset" nil 0)
    ("each" "Each" nil 0)
    ("else" "Else" nil 0)
    ("elseif" "ElseIf" nil 0)
    ("end" "End" nil 3)
    ("environ" "Environ" nil 0)
    ("eof" "EOF" nil 0)
    ("erase" "Erase" nil 0)
    ("err" "Err" nil 0)
    ("error" "Error" nil 0)
    ("exit" "Exit" nil 0)
    ("exp" "Exp" nil 0)
    ("false" "False" nil 0)
    ("field" "Field" nil 0)
    ("fields" "Fields" nil 0)
    ("fileattr" "FileAttr" nil 0)
    ("filecopy" "FileCopy" nil 0)
    ("filedatetime" "FileDateTime" nil 0)
    ("filelen" "FileLen" nil 0)
    ("fix" "Fix" nil 0)
    ("font" "Font" nil 0)
    ("for" "For" nil 1)
    ("form" "Form" nil 0)
    ("format" "Format" nil 0)
    ("forms" "Forms" nil 0)
    ("formtemplate" "FormTemplate" nil 0)
    ("freefile" "FreeFile" nil 0)
    ("freelocks" "FreeLocks" nil 0)
    ("function" "Function" nil 0)
    ("fv" "FV" nil 0)
    ("get" "Get" nil 0)
    ("getallsettings" "GetAllSettings" nil 0)
    ("getattr" "GetAttr" nil 0)
    ("getobject" "GetObject" nil 0)
    ("getsetting" "GetSetting" nil 0)
    ("gosub" "GoSub" nil 0)
    ("goto" "GoTo" nil 0)
    ("group" "Group" nil 0)
    ("groups" "Groups" nil 0)
    ("hex" "Hex" nil 0)
    ("hour" "Hour" nil 0)
    ("if" "If" nil 4)
    ("iif" "IIf" nil 0)
    ("imestatus" "IMEStatus" nil 0)
    ("input" "Input" nil 0)
    ("instr" "InStr" nil 0)
    ("int" "Int" nil 0)
    ("integer" "Integer" nil 0)
    ("ipmt" "IPmt" nil 0)
    ("irr" "IRR" nil 0)
    ("is" "Is" nil 0)
    ("isarray" "IsArray" nil 0)
    ("isdate" "IsDate" nil 0)
    ("isempty" "IsEmpty" nil 0)
    ("iserror" "IsError" nil 0)
    ("ismissing" "IsMissing" nil 0)
    ("isnull" "IsNull" nil 0)
    ("isnumeric" "IsNumeric" nil 0)
    ("isobject" "IsObject" nil 0)
    ("kill" "Kill" nil 0)
    ("lbound" "LBound" nil 0)
    ("lcase" "LCase" nil 0)
    ("left" "Left" nil 0)
    ("len" "Len" nil 0)
    ("let" "Let" nil 0)
    ("like" "Like" nil 0)
    ("line" "Line" nil 0)
    ("load" "Load" nil 0)
    ("loadpicture" "LoadPicture" nil 0)
    ("loadresdata" "LoadResData" nil 0)
    ("loadrespicture" "LoadResPicture" nil 0)
    ("loadresstring" "LoadResString" nil 0)
    ("loc" "Loc" nil 0)
    ("lock" "Lock" nil 0)
    ("lof" "LOF" nil 0)
    ("log" "Log" nil 0)
    ("long" "Long" nil 0)
    ("loop" "Loop" nil 0)
    ("lset" "LSet" nil 0)
    ("ltrim" "LTrim" nil 0)
    ("mdiform" "MDIForm" nil 0)
    ("me" "Me" nil 0)
    ("menuitems" "MenuItems" nil 0)
    ("menuline" "MenuLine" nil 0)
    ("mid" "Mid" nil 0)
    ("minute" "Minute" nil 0)
    ("mirr" "MIRR" nil 0)
    ("mkdir" "MkDir" nil 0)
    ("month" "Month" nil 0)
    ("msgbox" "MsgBox" nil 0)
    ("name" "Name" nil 0)
    ("new" "New" nil 0)
    ("next" "Next" nil 4)
    ("now" "Now" nil 0)
    ("nper" "NPer" nil 0)
    ("npv" "NPV" nil 0)
    ("oct" "Oct" nil 0)
    ("on" "On" nil 0)
    ("open" "Open" nil 0)
    ("opendatabase" "OpenDatabase" nil 0)
    ("operator" "Operator" nil 0)
    ("option" "Option" nil 0)
    ("parameter" "Parameter" nil 0)
    ("parameters" "Parameters" nil 0)
    ("partition" "Partition" nil 0)
    ("picture" "Picture" nil 0)
    ("pmt" "Pmt" nil 0)
    ("ppmt" "PPmt" nil 0)
    ("print" "Print" nil 0)
    ("printer" "Printer" nil 0)
    ("printers" "Printers" nil 0)
    ("private" "Private" nil 0)
    ("projecttemplate" "ProjectTemplate" nil 0)
    ("properties" "Properties" nil 0)
    ("public" "Public" nil 0)
    ("put" "Put" nil 0)
    ("pv" "PV" nil 0)
    ("qbcolor" "QBColor" nil 0)
    ("querydef" "QueryDef" nil 0)
    ("querydefs" "QueryDefs" nil 0)
    ("randomize" "Randomize" nil 0)
    ("rate" "Rate" nil 0)
    ("recordset" "Recordset" nil 0)
    ("recordsets" "Recordsets" nil 0)
    ("redim" "ReDim" nil 0)
    ("registerdatabase" "RegisterDatabase" nil 0)
    ("relation" "Relation" nil 0)
    ("relations" "Relations" nil 0)
    ("rem" "Rem" nil 0)
    ("repairdatabase" "RepairDatabase" nil 0)
    ("reset" "Reset" nil 0)
    ("resume" "Resume" nil 0)
    ("return" "Return" nil 0)
    ("right" "Right" nil 0)
    ("rmdir" "RmDir" nil 0)
    ("rnd" "Rnd" nil 0)
    ("rollback" "Rollback" nil 0)
    ("rowbuffer" "RowBuffer" nil 0)
    ("rset" "RSet" nil 0)
    ("rtrim" "RTrim" nil 0)
    ("savepicture" "SavePicture" nil 0)
    ("savesetting" "SaveSetting" nil 0)
    ("screen" "Screen" nil 0)
    ("second" "Second" nil 0)
    ("seek" "Seek" nil 0)
    ("selbookmarks" "SelBookmarks" nil 0)
    ("select" "Select" nil 0)
    ("selectedcomponents" "SelectedComponents" nil 0)
    ("sendkeys" "SendKeys" nil 0)
    ("set" "Set" nil 0)
    ("setattr" "SetAttr" nil 0)
    ("setdataaccessoption" "SetDataAccessOption" nil 0)
    ("setdefaultworkspace" "SetDefaultWorkspace" nil 0)
    ("sgn" "Sgn" nil 0)
    ("shell" "Shell" nil 0)
    ("sin" "Sin" nil 0)
    ("single" "Single" nil 0)
    ("sln" "SLN" nil 0)
    ("snapshot" "Snapshot" nil 0)
    ("space" "Space" nil 0)
    ("spc" "Spc" nil 0)
    ("sqr" "Sqr" nil 0)
    ("static" "Static" nil 0)
    ("stop" "Stop" nil 0)
    ("str" "Str" nil 0)
    ("strcomp" "StrComp" nil 0)
    ("strconv" "StrConv" nil 0)
    ("string" "String" nil 0)
    ("sub" "Sub" nil 8)
    ("submenu" "SubMenu" nil 0)
    ("switch" "Switch" nil 0)
    ("syd" "SYD" nil 0)
    ("tab" "Tab" nil 0)
    ("table" "Table" nil 0)
    ("tabledef" "TableDef" nil 0)
    ("tabledefs" "TableDefs" nil 0)
    ("tan" "Tan" nil 0)
    ("then" "Then" nil 2)
    ("time" "Time" nil 0)
    ("timer" "Timer" nil 0)
    ("timeserial" "TimeSerial" nil 0)
    ("timevalue" "TimeValue" nil 0)
    ("to" "To" nil 1)
    ("trim" "Trim" nil 0)
    ("true" "True" nil 0)
    ("type" "Type" nil 0)
    ("typename" "TypeName" nil 0)
    ("ubound" "UBound" nil 0)
    ("ucase" "UCase" nil 0)
    ("unload" "Unload" nil 0)
    ("unlock" "Unlock" nil 0)
    ("val" "Val" nil 0)
    ("vartype" "VarType" nil 0)
    ("verb" "Verb" nil 0)
    ("weekday" "Weekday" nil 0)
    ("wend" "Wend" nil 0)
    ("while" "While" nil 0)
    ("width" "Width" nil 0)
    ("with" "With" nil 0)
    ("workspace" "Workspace" nil 0)
    ("workspaces" "Workspaces" nil 0)
    ("write" "Write" nil 0)
    ("year" "Year" nil 0)
    ))

