#!/usr/bin/env python3

# https://github.com/albertlauncher/python/blob/master/CopyQ.py

import sys
import json
import subprocess as sp

copyq_script_getAll = r"""
var result=[];
for ( var i = 0; i < size(); ++i ) {
    var obj = {};
    obj.row = i;
    obj.mimetypes = str(read("?", i)).split("\n");
    obj.mimetypes.pop();
    obj.text = str(read(i));
    result.push(obj);
}
JSON.stringify(result);
"""


if __name__ == '__main__':
    if len(sys.argv) <= 1:
        exit()
    p = sp.run('copyq -'.split(), input=copyq_script_getAll,
               encoding='utf-8', stdout=sp.PIPE, stderr=sp.PIPE)
    json_arr = json.loads(p.stdout)

    items = []
    for json_obj in json_arr:
        text = json_obj['text']
        text = " ".join(filter(None, text.replace("\n", " ").split(" ")))
        items.append(text)

    rofi_input = '\n'.join(x for x in items)

    if sys.argv[1] == 'list':
        print(rofi_input)
    if sys.argv[1] == 'decode':
        input = sys.argv[2]
        num = 0
        for s in items:
            if s == input:
                break
            num += 1
        sp.run(f'copyq select({num});'.split(),
               encoding='utf-8', stdout=sp.PIPE, stderr=sp.PIPE)

    # p = sp.run(rofi, input=rofi_input, encoding='utf-8', stdout=sp.PIPE, stderr=sp.PIPE)
    # if p.returncode == 0:
    #     num = p.stdout.strip()
    #     sp.run(f'copyq select({num});'.split(),
    #            encoding='utf-8', stdout=sp.PIPE, stderr=sp.PIPE)
