[[plugins]]
repo = 'xolox/vim-lua-ftplugin'

[[plugins]]
repo = "puremourning/vimspector"
on_ft = ["python", "javascript"]
build = "./install_gadget.py --enable-python --force-enable-noden_ft = 'lua' --force-enable-php --force-enable-java --enable-go"

