     * @SuppressWarnings(Superglobals)
     * @SuppressWarnings(CamelCaseClassName)
     * @SuppressWarnings(CamelCasePropertyName)
     * @SuppressWarnings(CamelCaseMethodName)
     * @SuppressWarnings(CamelCaseParameterName)
     * @SuppressWarnings(CamelCaseVariableName)
