#!/bin/bash
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid

export APACHE_LOCK_DIR=/var/run/apache2/
export APACHE_PID_FILE=/var/run/apache2/apache2.pid
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data
export APACHE_LOG_DIR=/var/log/apache2/
exec apache2 -DFOREGROUND
