services:
  database:
    image: postgres:14
    container_name: database
    tty: true
    restart: always
    ports:
      - 5432:5432
    volumes:
      - database-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
volumes:
  database-store:
