# Credit: https://github.com/mooz/xkeysnail/blob/bf3c93b4fe6efd42893db4e6588e5ef1c4909cfb/example/config.py#L62-L125
# x11 -> wmctrl -x -l
# wayland+Gnome -> A-F2, lg
# wayland+kde -> swaymsg -t get_tree, niri msg windows
# virtual_modifiers:
#   - CapsLock
shared:
  terminals: &terminals
    - gvim.Gvim
    - gnome-terminal-server
    - floorp
    - Gnome-terminal
    - Emacs
    - code.Code
    - gvim
    - goneovim.goneovim
    - org.gnome.Terminal.desktop
    - gnome-terminal-server.Gnome-terminal
    - Alacritty.Alacritty
    - obsidian.obsidian
    - Vivaldi-stable
modmap:
  - name: CapsLock to Ctrl_L
    remap:
      CapsLock: Ctrl_L
keymap:
  - name: Emacs
    application:
      not: *terminals
    remap:
      # Cursor
      C-b: { with_mark: left }
      C-f: { with_mark: right }
      C-p: { with_mark: up }
      C-n: { with_mark: down }
      # Forward/Backward word
      # M-b: { with_mark: C-left }
      # M-f: { with_mark: C-right }
      # Beginning/End of line
      C-a: { with_mark: home }
      C-e: { with_mark: end }
      # Page up/down
      # M-v: { with_mark: pageup }
      # C-v: { with_mark: pagedown }
      # Beginning/End of file
      # M-Shift-comma: { with_mark: C-home }
      # M-Shift-dot: { with_mark: C-end
      # Newline
      C-m: enter
      C-j: enter
      C-o: [enter, left]
      # Copy
      C-w: [C-x, { set_mark: false }]
      # M-w: [C-c, { set_mark: false }]
      C-y: [C-v, { set_mark: false }]
      # Delete
      C-d: [delete, { set_mark: false }]
      # M-d: [C-delete, { set_mark: false }]
      # Kill line
      # C-k: [Shift-end, C-x, { set_mark: false }]
      # Kill word backward
      # Alt-backspace: [C-backspace, {set_mark: false}]
      # # set mark next word continuously.
      # C-M-space: [C-Shift-right, {set_mark: true}]
      # Undo
      # C-slash: [C-z, { set_mark: false }]
      # C-Shift-ro: C-z
      # Mark
      # C-space: { set_mark: true }
      # Search
      C-s: C-f
      C-r: Shift-F3
      # M-Shift-5: C-h
      # Cancel
      C-g: [esc, { set_mark: false }]
      # C-x YYY
      # C-x:
      #   remap:
      #     # C-x h (select all)
      #     h: [C-home, C-a, { set_mark: true }]
      #     # C-x C-f (open)
      #     C-f: C-o
      #     # C-x C-s (save)
      #     C-s: C-s
      #     # C-x k (kill tab)
      #     k: C-f4
      #     # C-x C-c (exit)
      #     C-c: C-q
      #     # C-x u (undo)
      #     u: [C-z, { set_mark: false }]
  - name: Cmd key mapping
    application:
      not: *terminals
    remap:
      # KEY_MUHENKAN
      WIN-a: C-a
      WIN-b: C-b
      WIN-c: C-c
      WIN-d: C-d
      WIN-e: C-e
      WIN-f: C-f
      WIN-g: C-g
      WIN-h: C-h
      WIN-i: C-i
      WIN-j: C-j
      WIN-k: C-k
      WIN-l: C-l
      WIN-m: C-m
      WIN-n: C-n
      WIN-o: C-o
      WIN-p: C-p
      WIN-q: C-q
      WIN-r: C-r
      WIN-s: C-s
      WIN-t: C-t
      WIN-u: C-u
      WIN-v: C-v
      WIN-w: C-w
      WIN-x: C-x
      WIN-y: C-y
      # Alt-z: C-z
      WIN-z: C-z
