#!/usr/bin/env zsh

function cdf() {
  if [ x$1 = x ];then
    return
  fi
  cd $*
}

function _cdf() {
reply=( \
  #`cat <<EOM | osascript | sort -u | perl -ne '$_ =~ s/([0x3040-0x309f]|[0x30a0-0x30ff]|[0x4e00-9fff])/\$1/g; print;'
  #`cat <<EOM | osascript | sort -u | perl -ne '$_ =~ s/(\p{InHiragana}|\p{InKatakana})/\\$1/g; print;'
  `cat <<EOM | osascript | sort -u
tell application "Finder"
  set cnt to count of windows
  set paths to ""
  repeat with i from 1 to cnt
    set pt to POSIX path of (target of window i as Unicode Text)
    if paths is "" then
      set paths to pt
    else
      set paths to paths & "\n" & pt
    end if
  end repeat
  get paths
end tell
EOM
`\
  )
}

if which osascript > /dev/null 2>&1 ; then
  compctl -K _cdf cdf
fi

