(require 'helm-descbinds)
(helm-descbinds-mode t)
;; (require 'helm-migemo)
;; (setq helm-use-migemo t)
(require 'helm-ag)
(require 'helm-dired-recent-dirs)

(let ((key-and-func
       `((,(kbd "C-x b")   helm-for-files)
		 (,(kbd "C-x C-b") helm-mini)
		 (,(kbd "C-x C-f") helm-find-files)
		 (,(kbd "C-x b") helm-mini)
         (,(kbd "C-^")   helm-c-apropos)
         (,(kbd "C-;")   helm-resume)
         (,(kbd "M-s")   helm-occur)
         (,(kbd "M-x")   helm-M-x)
         (,(kbd "M-y")   helm-show-kill-ring)
         (,(kbd "M-z")   helm-do-grep)
         (,(kbd "C-S-h") helm-descbinds)
         (,(kbd "C-c C-r") helm-resume)
		 )))
  (loop for (key func) in key-and-func
        do (global-set-key key func)))
