source "https://rubygems.org"
# source :rubyforge
# source :gemcutter

# source :rubygems
# source :rubyforge
# source :gemcutter

gem 'sqlite3'
# gem "dm-is-localizable", :git => "git://github.com/snusnu/dm-is-localizable.git"
# group :development, :test do
#   gem 'rspec-rails'
#   gem 'spring-commands-rspec'
# end

