source "https://rubygems.org"
# source :rubyforge
# source :gemcutter

# source :rubygems
# source :rubyforge
# source :gemcutter

gem 'sinatra', '0.9.4'
gem 'haml'
# gem "dm-is-localizable", :git => "git://github.com/snusnu/dm-is-localizable.git"

