# -*- mode: ruby -*-
# vim: set ft=ruby :
# Don't forget to run this vagrant command first
# vagrant ssh-config >> ~/.ssh/config

# for capistrano
# set :user, 'vagrant'
# set :run_method, :sudo
# 
# role :app, '192.168.33.10"
# 
# ssh_options[:keys] = `vagrant ssh_config | grep IdentityFile`.split.last

Vagrant::Config.run do |config|
  config.vm.box = "centos-5.7-x86_64"
  # config.vm.box_url = "http://domain.com/path/to/above.box"
  # config.vm.boot_mode = :gui
  config.vm.network :hostonly, "192.168.33.10"
  # config.vm.network :bridged
  # config.vm.forward_port 80, 8080
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.add_recipe "vim"
    chef.add_recipe "zsh"
    chef.add_recipe "screen"
    chef.add_recipe "build-essential"
    chef.add_recipe "tmux"
    chef.add_recipe "openssl"
    chef.add_recipe "vim"
    # chef.add_recipe "php"
    # chef.add_recipe "apache2"
    chef.add_recipe "mysql::server"
    # chef.add_role "web"
    #
    # You may also specify custom JSON attributes:
    chef.json.merge! :mysql => {
        :server_root_password => "admin",
        :server_repl_password => "repl",
        :server_debian_password => "deb",
        :bind_address => "0.0.0.0",
      }
  end

  config.vm.customize ["modifyvm", :id, "--name", "vagrant_imagoo", "--memory", "1024"]
  # config.vm.provision :chef_client do |chef|
  #   chef.chef_server_url = "https://api.opscode.com/organizations/ORGNAME"
  #   chef.validation_key_path = "ORGNAME-validator.pem"
  # end
  #   chef.validation_client_name = "ORGNAME-validator"
end

