# vim:fdm=marker sw=2 ts=2 ft=toml expandtab:
[[plugins]]
repo = 'nvim-telescope/telescope-ui-select.nvim'
[[plugins]]
repo = "fdschmidt93/telescope-egrepify.nvim"
[[plugins]]
repo = 'folke/trouble.nvim'
[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
build = 'make'
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = '''
lua <<EOF
local telescope = require("telescope")
local actions = require('telescope.actions')

telescope.load_extension("ui-select")
telescope.setup {
  pickers = {
    live_grep = {
      mappings = {
        n = {
          ['q'] = require('telescope.actions').close,
        },
        i = {
          ['<C-o>'] = actions.send_to_qflist + actions.open_qflist,
          ['<C-l>'] = actions.send_to_loclist + actions.open_loclist,
          ['<C-u>'] = '<Esc>^wDA',
        },
      },
    },
  },
  extensions = {
    ['ui-select'] = {
      require('telescope.themes').get_dropdown({})
    }
  }
}
local function egrepify()
  require('telescope').extensions.egrepify.egrepify({})
end
local util = require('my/util')
local nmap = util.nmap
local nnoremap = util.nnoremap
local builtin = require('telescope.builtin')
nnoremap('[!zz]', function() end)
-- nmap('f', '[!zz]')
vim.cmd('nmap f [!zz]')
nnoremap('[!zz]f', 'f')
nnoremap('[!zz]j', builtin.buffers)
nnoremap('[!zz]l', builtin.find_files)
nnoremap('[!zz]h', builtin.help_tags)
nnoremap('[!zz]gr', builtin.live_grep)
nnoremap('[!zz]gd', builtin.diagnostics)
nnoremap('[!zz]gl', builtin.current_buffer_fuzzy_find)
nnoremap('[!zz]gs', builtin.lsp_document_symbols)
nnoremap('[!zz]e', builtin.resume)
nnoremap('[!zz]ge', builtin.resume)
nnoremap('[!zz]hc', builtin.commands)
nnoremap('[!zz]m', builtin.oldfiles)
nnoremap('[!zz]gr', egrepify)

EOF
'''
