fpath+=~/.zsh/zfunc/commands
autoload -Uz cdd
autoload -Uz cdgem
fpath+=~/.zsh/zfunc/peco
autoload -Uz peco-attach-gdb-pid
zle -N peco-attach-gdb-pid
autoload -Uz peco-git-changed-files
zle -N peco-git-changed-files
autoload -Uz peco-git-fixup
zle -N peco-git-fixup
autoload -Uz peco-git-issue-show-redmine
zle -N peco-git-issue-show-redmine
autoload -Uz peco-git-log
zle -N peco-git-log
autoload -Uz peco-git-ls-files
zle -N peco-git-ls-files
autoload -Uz peco-git-rebase-i
zle -N peco-git-rebase-i
autoload -Uz peco-git-recent-all-branches
zle -N peco-git-recent-all-branches
autoload -Uz peco-git-recent-branches
zle -N peco-git-recent-branches
autoload -Uz peco-info-homebrew
zle -N peco-info-homebrew
autoload -Uz peco-info-homebrew-cask
zle -N peco-info-homebrew-cask
autoload -Uz peco-install-homebrew
zle -N peco-install-homebrew
autoload -Uz peco-install-homebrew-cask
zle -N peco-install-homebrew-cask
autoload -Uz peco-open-bundle-gem
zle -N peco-open-bundle-gem
autoload -Uz peco-open-homebrew
zle -N peco-open-homebrew
autoload -Uz peco-open-homebrew-cask
zle -N peco-open-homebrew-cask
autoload -Uz peco-search-clipmenu
zle -N peco-search-clipmenu
autoload -Uz peco-search-document
zle -N peco-search-document
autoload -Uz peco-search-locate
zle -N peco-search-locate
autoload -Uz peco-select-ghq
zle -N peco-select-ghq
autoload -Uz peco-select-gui-window
zle -N peco-select-gui-window
autoload -Uz peco-select-history
zle -N peco-select-history
autoload -Uz peco-select-homebrew-plist
zle -N peco-select-homebrew-plist
autoload -Uz peco-select-logfiles
zle -N peco-select-logfiles
autoload -Uz peco-select-ls-la
zle -N peco-select-ls-la
autoload -Uz peco-select-plist-all
zle -N peco-select-plist-all
autoload -Uz peco-select-plist-system
zle -N peco-select-plist-system
autoload -Uz peco-select-plist-user
zle -N peco-select-plist-user
autoload -Uz peco-select-ps-kill
zle -N peco-select-ps-kill
autoload -Uz peco-select-ps-kill-hup
zle -N peco-select-ps-kill-hup
autoload -Uz peco-select-ps-pid
zle -N peco-select-ps-pid
autoload -Uz peco-select-raketask
zle -N peco-select-raketask
autoload -Uz peco-select-raketask-all
zle -N peco-select-raketask-all
autoload -Uz peco-select-snippets
zle -N peco-select-snippets
autoload -Uz peco-select-ssh-host
zle -N peco-select-ssh-host
autoload -Uz peco-select-zle
zle -N peco-select-zle
autoload -Uz peco-select-zle-git
zle -N peco-select-zle-git
